### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: android.support.v8.renderscript.RenderScript

### ISSUE THREAD

**Issue by qiang** [500px/500px-android-blur#15] opened 2015-12-23 07:53 UTC
``` java
  Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.fivehundredpx.android.blur.BlurringView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                           at android.view.View.inflate(View.java:17504)
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.initView(ProvideCluePager.java:26)
                                                                           at com.fivetv.elementary.view.pager.BasePager.<init>(BasePager.java:31)
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.<init>(ProvideCluePager.java:21)
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.initView(MediaPlayerActivity.java:134)
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.onCreate(MediaPlayerActivity.java:67)
                                                                           at android.app.Activity.performCreate(Activity.java:5249)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5065) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.view.View.inflate(View.java:17504) 
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.initView(ProvideCluePager.java:26) 
                                                                           at com.fivetv.elementary.view.pager.BasePager.<init>(BasePager.java:31) 
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.<init>(ProvideCluePager.java:21) 
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.initView(MediaPlayerActivity.java:134) 
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.onCreate(MediaPlayerActivity.java:67) 
                                                                           at android.app.Activity.performCreate(Activity.java:5249) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5065) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.NoClassDefFoundError: android.support.v8.renderscript.RenderScript
                                                                           at com.fivehundredpx.android.blur.BlurringView.initializeRenderScript(BlurringView.java:98)
                                                                           at com.fivehundredpx.android.blur.BlurringView.<init>(BlurringView.java:37)
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.view.View.inflate(View.java:17504) 
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.initView(ProvideCluePager.java:26) 
                                                                           at com.fivetv.elementary.view.pager.BasePager.<init>(BasePager.java:31) 
                                                                           at com.fivetv.elementary.view.pager.ProvideCluePager.<init>(ProvideCluePager.java:21) 
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.initView(MediaPlayerActivity.java:134) 
                                                                           at com.fivetv.elementary.activity.MediaPlayerActivity.onCreate(MediaPlayerActivity.java:67) 
                                                                           at android.app.Activity.performCreate(Activity.java:5249) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5065) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
```

I have already add the 
        "renderscriptTargetApi 20"
        "renderscriptSupportModeEnabled true"
in my gradle file . but i still got that error ，why?

**Comment by zbzbhahae** [comment] 2015-12-25 03:17
add sdk/build-tools/x.x.x/renderscript/lib/renderscript-v8.jar  to your project
for lower version of android 
also need librsjni.so libRSSupport.so at sdk/build-tools/x.x.x/renderscript/lib/xxx/armeabi-v7a ...

**Comment by goodofficedevsenam** [comment] 2015-12-27 09:04
Simply replace all the renderscript imports from the BlurringView.java class with : import android.renderscript.*;

**Comment by Reza-Rg** [comment] 2016-01-14 16:36
If you are using with `minifyEnabled true`, then you have to add proguard rule as below:
`-keep class android.support.v8.renderscript.** { *; }`

**Comment by JackyAndroid** [comment] 2016-03-17 05:11
@niyingxunzong if you project is module，
try  " renderscriptTargetApi 21
        renderscriptSupportModeEnabled true" in your app gradle

**Comment by breadadams** [comment] 2016-11-04 17:47
~~Is there an _official_ fix for this?~~

@JackyAndroid's solution gets rid of the errors for me!

**Comment by csbubbles** [comment] 2016-12-14 00:05
I don't have minified enabled and I am still getting the same error. Any help? It appears the bug has been open for a year already...

**Comment by peerless2012** [comment] 2017-01-03 08:06
@Reza-Rg 感谢，解决了我的问题。发现是在release的时候 minifyEnabled = true导致这个问题

**Comment by Pranoy1c** [comment] 2018-09-12 04:33
Adding 

`renderscriptTargetApi 21
renderscriptSupportModeEnabled true`

to the build.gradle's defaultConfig section worked!

**Comment by AliNajafi1998** [comment] 2019-03-24 07:16
@JackyAndroid 
Thanks :+1:

**Closed as completed** 2019-03-25 19:02 UTC

**Comment by jushenziao** [comment] 2019-09-09 11:41
> @niyingxunzong if you project is module，
> try " renderscriptTargetApi 21
> renderscriptSupportModeEnabled true" in your app gradle

Thanks! It is good. but ,could you tell me the root cause.

**Comment by mnewlive** [comment] 2019-10-15 13:48
> If you are using with `minifyEnabled true`, then you have to add proguard rule as below:
> `-keep class android.support.v8.renderscript.** { *; }`

Also if u use AndroidX, u need to use:
`-keep class androidx.renderscript.** { *; }`

**Comment by HardyInfotech** [comment] 2023-10-10 04:39
If you use target sdk = 33,

renderscriptTargetApi 33 renderscriptSupportModeEnabled true

use of this proguard - 
# RenderScript to be safe on "native callback" side
-keep class androidx.renderscript.** { *; }
-keep class android.renderscript.** { *; }
